import type {Product, Receipt, StoreSettings} from './types';

const now = Date.now();
const hours = (count: number) => count * 60 * 60 * 1000;

export const seedProducts: Product[] = [
  {
    id: 'p1',
    name: 'Milk Tea',
    category: 'Drinks',
    price: 250,
    stock: 18,
    unit: 'cup',
    code: 'MT2401',
    color: '#173A63',
    description: 'Fresh brewed milk tea with fast-moving demand.',
  },
  {
    id: 'p2',
    name: 'Mineral Water',
    category: 'Essentials',
    price: 120,
    stock: 42,
    unit: 'bottle',
    code: 'MW1092',
    color: '#0A6E6E',
    description: '500ml bottle kept near the front counter.',
  },
  {
    id: 'p3',
    name: 'Chocolate Biscuit',
    category: 'Snacks',
    price: 180,
    stock: 9,
    unit: 'pack',
    code: 'CB5521',
    color: '#8C5A2B',
    description: 'Impulse purchase snack with strong evening sales.',
  },
  {
    id: 'p4',
    name: 'USB Cable',
    category: 'Accessories',
    price: 850,
    stock: 6,
    unit: 'piece',
    code: 'UC8804',
    color: '#3E4C6B',
    description: 'Fast moving tech accessory near cashier desk.',
  },
  {
    id: 'p5',
    name: 'Notebook A5',
    category: 'Stationery',
    price: 320,
    stock: 14,
    unit: 'book',
    code: 'NB2044',
    color: '#5E4BB7',
    description: 'Everyday notebook for school and office shoppers.',
  },
  {
    id: 'p6',
    name: 'Brown Bread',
    category: 'Bakery',
    price: 210,
    stock: 4,
    unit: 'loaf',
    code: 'BB6682',
    color: '#9A5A32',
    description: 'Low stock bakery item that needs daily adjustment.',
  },
  {
    id: 'p7',
    name: 'Laundry Soap',
    category: 'Home',
    price: 430,
    stock: 23,
    unit: 'bar',
    code: 'LS9190',
    color: '#2E7A92',
    description: 'Reliable household item with repeat buyers.',
  },
];

export const seedReceipts: Receipt[] = [
  {
    id: 'r1',
    number: '#0007',
    items: [
      {productId: 'p1', name: 'Milk Tea', price: 250, quantity: 2},
      {productId: 'p3', name: 'Chocolate Biscuit', price: 180, quantity: 1},
    ],
    subtotal: 680,
    tax: 0,
    total: 680,
    paidAmount: 680,
    changeDue: 0,
    paymentMethod: 'cash',
    issuedAt: new Date(now - hours(1)).toISOString(),
  },
  {
    id: 'r2',
    number: '#0006',
    items: [{productId: 'p2', name: 'Mineral Water', price: 120, quantity: 4}],
    subtotal: 480,
    tax: 0,
    total: 480,
    paidAmount: 480,
    changeDue: 0,
    paymentMethod: 'card',
    issuedAt: new Date(now - hours(5)).toISOString(),
  },
  {
    id: 'r3',
    number: '#0005',
    items: [{productId: 'p4', name: 'USB Cable', price: 850, quantity: 1}],
    subtotal: 850,
    tax: 0,
    total: 850,
    paidAmount: 850,
    changeDue: 0,
    paymentMethod: 'card',
    issuedAt: new Date(now - hours(26)).toISOString(),
  },
  {
    id: 'r4',
    number: '#0004',
    items: [
      {productId: 'p5', name: 'Notebook A5', price: 320, quantity: 2},
      {productId: 'p2', name: 'Mineral Water', price: 120, quantity: 1},
    ],
    subtotal: 760,
    tax: 0,
    total: 760,
    paidAmount: 760,
    changeDue: 0,
    paymentMethod: 'cash',
    issuedAt: new Date(now - hours(50)).toISOString(),
  },
  {
    id: 'r5',
    number: '#0003',
    items: [{productId: 'p7', name: 'Laundry Soap', price: 430, quantity: 3}],
    subtotal: 1290,
    tax: 0,
    total: 1290,
    paidAmount: 1290,
    changeDue: 0,
    paymentMethod: 'split',
    issuedAt: new Date(now - hours(73)).toISOString(),
  },
];

export const seedSettings: StoreSettings = {
  storeName: 'Corner Shop POS',
  storeSubtitle: 'Offline counter mode',
  printerName: 'Thermal Printer T82',
  printerConnected: true,
  autoPrint: true,
  currency: 'LKR',
};
